automation:
  # questa prima automazione va modificata inserendo il proprio chat id
  - id: tg avvio server
    alias: tg avvio server
    triggers:
      - event: start
        trigger: homeassistant
    actions:
      - delay:
          hours: 0
          minutes: 0
          seconds: 15
          milliseconds: 0
      - action: telegram_bot.send_message
        data:
          target:
            - "123456789"
          message: "✅ *Home Assistant si è avviato* ✅
          inline_keyboard:
              - "{{ \"\\U0001F3E0\" }} Avvia il bot:/start"
