# Cambiare l'entita alarm_control_panel.home con la vostra
# alle righe 14 19 24
# cambiare il taget inserendo il proprio chat id
# come spiegato nei pre requisiti.

automation:
  ############### Notifica Allarme Inserito/Disinserito
  - id: tgnotificainfoallarme
    alias: tg notifica allarme
    ##hide_entity: true
    triggers:
      - trigger: state
        entity_id:
          - alarm_control_panel.home
        to: disarmed
        id: alarm-disarmed
      - trigger: state
        entity_id:
          - alarm_control_panel.home
        to: armed_home
        id: alarm-armed-home
      - trigger: state
        entity_id:
          - alarm_control_panel.home
        to: armed_away
        id: alarm-armed-away
    actions:
      - choose:
          ############### ID ALARM DISARMED ###############
          - conditions:
              - condition: trigger
                id:
                  - alarm-disarmed
            sequence:
              - action: telegram_bot.send_message
                data:
                  target:
                    - "123456789"
                  message: >-
                    *Allarme disattivato*
                    {{'\n'}}
                    alle ore {{ states('sensor.time') }}

          ############### ID ALARM ARMED HOME ###############
          - conditions:
              - condition: trigger
                id:
                  - alarm-armed-home
            sequence:
              - action: telegram_bot.send_message
                data:
                  target:
                    - "123456789"
                  message: >-
                    *Allarme attivato (HOME)*
                    {{'\n'}}
                    alle ore {{ states('sensor.time') }}

          ############### ID ALARM ARMED AWAY ###############
          - conditions:
              - condition: trigger
                id:
                  - alarm-armed-away
            sequence:
              - action: telegram_bot.send_message
                data:
                  target:
                    - "123456789"
                  message: >-
                    *ALLARME ATTIVATO (FUORI CASA)*
                    {{'\n'}}
                    alle ore {{ states('sensor.time') }}
