automation:
  - id: tgsensori
    alias: tg sensori
    #hide_entity: true
    triggers:
      - trigger: event
        event_type: telegram_command
        event_data:
          command: /sensori
        id: sensori
      - trigger: event
        event_type: telegram_callback
        event_data:
          data: /sensori
        id: sensori_callback
      - trigger: event
        event_type: telegram_callback
        event_data:
          data: /aggiorna_sensori
        id: aggiorna_sensori
    actions:
      - choose:
          ############### ID SENSORI ###############
          - conditions:
              - condition: trigger
                id:
                  - sensori
            sequence:
              - action: script.tg_script_sensori
                metadata: {}
                data:
                  trigger: "{{ trigger.event.data.user_id }}"
          ############### ID SENSORI CALLBACK ###############
          - conditions:
              - condition: trigger
                id:
                  - sensori_callback
            sequence:
              - action: telegram_bot.delete_message
                data:
                  message_id: "{{ trigger.event.data.message.message_id }}"
                  chat_id: "{{ trigger.event.data.user_id }}"
              - action: script.tg_script_sensori
                metadata: {}
                data:
                  trigger: "{{ trigger.event.data.user_id }}"
          ############### ID AGGIORNA SENSORI CALLBACK ###############
          - conditions:
              - condition: trigger
                id:
                  - aggiorna_sensori
            sequence:
              - action: script.tg_script_sensori_edit
                metadata: {}
                data:
                  message_id: "{{ trigger.event.data.message.message_id }}"
                  chat_id: "{{ trigger.event.data.user_id }}"

